In [1]:
import numpy as np

In [4]:
X = np.array([[1,2,3],
              [5,4,3],
              [7,6,2]
])
y = np.array([[8,2,4],
              [9,1,6],
              [3,2,7]
])

# 우리가 원하는 행렬곱 Xy는
print(X@y)

# x1과 y1의 내적  x1과 y2의 내적  x3와 y3의 내적
# x2과 y1의 내적  x2과 y2의 내적  x2와 y3의 내적
# x3과 y1의 내적  x3과 y2의 내적  x3와 y3의 내적
print(np.inner(X,y))
# 따라서 y의 transpose와 inner 하면 같은 행렬이 나온다.
print(np.inner(X,y.transpose()))


[[ 35  10  37]
 [ 85  20  65]
 [116  24  78]]
[[24 29 28]
 [60 67 44]
 [76 81 47]]
[[ 35  10  37]
 [ 85  20  65]
 [116  24  78]]


In [6]:
X = np.array([[1,0,1],
              [0,1,0],
              [1,1,0]
              ])
X = np.linalg.inv(X)
print(X)

[[ 0. -1.  1.]
 [ 0.  1.  0.]
 [ 1.  1. -1.]]


In [8]:
X=np.array([[1,0,1],
            [0,1,0]])
X = np.linalg.pinv(X)
print(X)

[[0.5 0. ]
 [0.  1. ]
 [0.5 0. ]]
